apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

commonlabels:
  app: ollama
  # app.kubernetes.io/component: ollama
  # app.kubernetes.io/instance: ollama
  app.kubernetes.io/name: ollama
  app.kubernetes.io/part-of: ollama

resources:
  - deployment.yaml
  - pvc.yaml
  - route.yaml
  - svc.yaml
