apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-ollama-namespace.yaml
  - 01-ollama-pvc.yaml
  - 02-ollama-serve-deployment.yaml 
  - 03-ollama-svc.yaml              
  - 04-ollama-route.yaml
