apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ollama-client-source
  annotations:
    app.openshift.io/vcs-ref: main
    app.openshift.io/vcs-uri: https://github.com/redhat-na-ssa/demo-ollama.git
  labels:
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.11-ubi8
spec:
  output:
    to:
      kind: ImageStreamTag
      name: ollama-client:latest
  runPolicy: SerialLatestOnly
  source:
    contextDir: /client
    git:
      ref: main
      uri: https://github.com/redhat-na-ssa/demo-ollama.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python:3.11-ubi8
        namespace: openshift
    type: Source
  triggers:
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange
