apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: ollama

commonLabels:
  app: ollama
  # app.kubernetes.io/component: ollama
  # app.kubernetes.io/instance: ollama
  app.kubernetes.io/name: ollama
  app.kubernetes.io/part-of: ollama

components:
- ../ollama-client
- ../ollama-serve

resources:
- namespace.yaml
